#Pipeline Configuration
pool:
    vmImage: 'ubuntu-latest'

trigger:
      - master

#Stages Configuration (to be ran sequentially)
stages:
  - stage: Master
    jobs:
    - job: Build
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'package'
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            
            echo 'Hello world'
            ls -la */**
      - publish: $(System.DefaultWorkingDirectory)/crm-auth-spring-boot-server/target/crm-auth-spring-boot-server-1.0.0-SNAPSHOT-bootable.jar
        artifact: authApp
  - stage: deploy
    jobs:
    - deployment: Deploy
      displayName: deploy Web App
      environment: 'ut'
      strategy:
      # default deployment strategy, more coming...
        runOnce:
          deploy:
            steps:
            - script: echo my first deployment
            - task: CopyFilesOverSSH@0
              inputs:
                sshEndpoint: 'ssh - RD3'
                contents: '*.jar'
                targetFolder: '/var/data/finuser/builds/'
                readyTimeout: '20000'
                failOnEmptySource: true
            - task: SSH@0
              inputs:
                sshEndpoint: 'ssh - RD3'
                runOptions: 'commands'
                commands: 'ls -la /var/data/finuser/builds'
                readyTimeout: '20000'

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

#- task: Maven@3
#  inputs:
#    mavenPomFile: 'pom.xml'
#    mavenOptions: '-Xmx3072m'
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.11'
#    jdkArchitectureOption: 'x64'
#    publishJUnitResults: true
#    testResultsFiles: '**/surefire-reports/TEST-*.xml'
#    goals: 'package'

#- task: Maven@3
#  inputs:
#    mavenPomFile: 'pom.xml'
#    publishJUnitResults: true
#    testResultsFiles: '**/surefire-reports/TEST-*.xml'
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.11'
#    mavenVersionOption: 'Default'
#    mavenOptions: '-Xmx3072m'
#    mavenAuthenticateFeed: false
#    effectivePomSkip: false
#    sonarQubeRunAnalysis: false



